version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tsathamid
      POSTGRES_DB: dockerDB
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready", "-d", "dockerDB"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
    working_dir: /server
    ports:
      - "8080:8080"
    environment:
      DB_HOSTNAME: db
    tty: true
