version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tsathamid
      POSTGRES_DB: dockerDB
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  server:
    build: .
    working_dir: /server
    restart: always
    ports:
       - "8080:8080"
    environment:
      DOCKER: "true"
